
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int cte_s = 7;
  public static final int read = 14;
  public static final int id = 3;
  public static final int coma = 13;
  public static final int cc = 12;
  public static final int asigna = 4;
  public static final int ca = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int promr = 9;
  public static final int cte = 2;
  public static final int parc = 6;
  public static final int pyc = 10;
  public static final int write = 8;
  public static final int para = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cte",
  "id",
  "asigna",
  "para",
  "parc",
  "cte_s",
  "write",
  "promr",
  "pyc",
  "ca",
  "cc",
  "coma",
  "read"
  };
}

